org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.workers.max=1
kotlin.daemon.jvmargs=-Xmx512m
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Work around Kotlin incremental compilation failing when the project and
# the Windows Pub cache are located on different drive letters.
kotlin.incremental=false
